version: "3"
services:
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    ports:
      - 8234:80
    depends_on:
      - pluginrepo
    networks:
      - pluginrepo_network
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
      - ./data/dl:/srv/dl
    environment:
      - VIRTUAL_HOST=localhost:8234
      - UPLOAD_SIZE=10m
      #- VIRTUAL_HOST=plugins.gbd-consult.de
      #- LETSENCRYPT_HOST=plugins.gbd-consult.de
      #- LETSENCRYPT_EMAIL=info@gbd-consult.de
  pluginrepo:
    build: .
    container_name: pluginrepo
    volumes:
      - ./data:/data
    #environment:
      #- GBD_PLUGIN_ROOT=https://plugins.gbd-consult.de/dl
      #- SECRET_KEY=putyoursecrethere!
    networks:
      pluginrepo_network:
        aliases:
          - pluginrepo
networks:
  pluginrepo_network:
